### ISSUE TITLE
Error while parsing data from csv file

### ISSUE THREAD

**Issue by w3slley** [hagnat/covid#3]
I've been getting this error when I clone the repository and use `make` to generate the text files:
```
=> generating portuguese wikipedia articles
php bin/wikipedia.php pt
   lookup last updated file
   extracting local data from CSV files...
PHP Warning:  fopen(/home/weslley/Documentos/covid/var/input/2020-05-10-brasil-covid-data.csv): failed to open stream: No such file or directory in /home/weslley/Documentos/covid/src/Infrastructure/CovidCsvReader.php on line 31
Unable to open CSV file=> generating english wikipedia artiles
php bin/wikipedia.php en
   lookup last updated file
   extracting local data from CSV files...
PHP Warning:  fopen(/home/weslley/Documentos/covid/var/input/2020-05-10-brasil-covid-data.csv): failed to open stream: No such file or directory in /home/weslley/Documentos/covid/src/Infrastructure/CovidCsvReader.php on line 31
Unable to open CSV file=> all tables generated!
```
I noticed that in the folder covid/var/input/ there is a file called `2020-05-11-brasil-covid-data.csv`, which is different from the one on the script. Are you also getting this error or is it just me? Thanks.

**Comment by hagnat** [comment]
hi. I was experimenting with some new things and you may have caught the script mid-modification. Sorry, i am not using branches for my own convenience, so i will try to create tags at least.

I have recently updated the script so there is no need to manually download the files. The script now downloads the XML and converts it to CSV (i may need to update it to detected if the ministry of health is once again releasing csv files).

I also added some new functionalities to the code, in order to speed up some parts of it, and allow me to add more features to it.

Please pull the latest version of the code, and try to run `make wikipedia/english` (the portuguese version is broken for now)

**Comment by w3slley** [comment]
Ok. Will do. I read the Readme about the ministry of health changing formats. Is it more tiresome to deal with the data as it is now?

**Comment by hagnat** [comment]
i liked how they organized the data before. It was cleaner, and simpler to use. Now they add national, state, and city level data in a single excel file. Since they are using excel, they could at least group them in a sheet for each level. This has created a lot of 'revisions' on data (me grouping what i shouldn't), that i am feeling kind of ashamed of introducing errors to wikipedia ;/

the latest version tries to deal with this issue. It is slower to parse the CSV file now, but at least i am more confident that the current data is correct.

**Comment by w3slley** [comment]
Makes sense. I'll give it a try later. I'm not having too much time to improve the Portugal script, but since there were no major changes since DGS added more statistics into the reports (total non confirmed cases, total suspected cases, under surveillance, etc), I think the script can stay as it is for now. 

If you need help doing some trivial task and want to subsidize it to me, just hit me a message and (if I'm able to) I would be glad to help.

**Comment by hagnat** [comment]
thanks for the offer
if there is anything i need, i will try to message ya :)
